/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3D/heroscooter.glb 
Author: neshallads (https://sketchfab.com/neshallads)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ola-electric-scooter-white-color-54a28e841f494f7496468f06aa36fbcb
Title: OLA Electric Scooter (White Color)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/heroscooter.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.wheels_Wheel_0.geometry} material={materials.Wheel} />
        <mesh geometry={nodes.second_color_Second_0.geometry} material={materials.Second} />
        <mesh geometry={nodes.main_color_Base_0.geometry} material={materials.Base} />
      </group>
    </group>
  )
}

useGLTF.preload('/heroscooter.glb')
